version: "3.8"
services:
  # myapp:
  #   build:
  #     context: deployment
  #   container_name: myapp
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - mynetwork
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - mynetwork
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 100m
  db_mysql:
    image: mysql:latest
    container_name: db_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: commerce_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - mynetwork
    # volumes:
    #   - db_mysql_volumes:/data/db_mysql
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500m
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - 1234:8080
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100m

# volumes:
#   db_mysql_volumes:

networks:
  mynetwork:
    driver: bridge